AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Splits s3 files into smaller parts

Parameters:
  Stack:
    Description: Stack name
    Type: String
    Default: content-api
  App:
    Description: Application name
    Type: String
    Default: s3-chunking-lambda
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - CODE
      - PROD
  OutputBucket:
    Description: Bucket to copy files to
    Type: String
    Default: gu-audio-logs
  DeployBucket:
    Description: Bucket to copy files to
    Type: String
    Default: content-api-dist
  MaxObjectSize:
    Description: Objects above this size in mb will be split
    Type: Number
  SourceBuckets:
    Description: List of the source bucket ARN permissions, e.g. 'arn:aws:s3::*:my-source-bucket-1/*,arn:aws:s3::*:my-source-bucket-2/*'
    Type: CommaDelimitedList
Resources:
  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${App}-${Stage}
      Description: Splits s3 files into smaller parts
      Runtime: nodejs8.10
      Handler: lambda.handler
      MemorySize: 512
      Timeout: 300
      Environment:
        Variables:
          Bucket: !Ref OutputBucket
          MaxObjectSize: !Ref MaxObjectSize
      CodeUri:
        Bucket: !Ref DeployBucket
        Key: !Sub ${Stack}/${Stage}/${App}/${App}.zip
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:ListObjects
            Resource:
              !Ref SourceBuckets
        - Statement:
            Effect: Allow
            Action:
              - s3:PutObject
            Resource:
              - !Sub "arn:aws:s3::*:${OutputBucket}/*"
